# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_carinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['-id'], 'verbose_name': '车辆品牌表', 'verbose_name_plural': '车辆品牌表'},
        ),
    ]
