# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-24 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20180824_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carinfo',
            options={'ordering': ['-id'], 'verbose_name': '车辆信息表', 'verbose_name_plural': '车辆信息表'},
        ),
    ]
