# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-08-28 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_auto_20180824_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinfo',
            name='isDelete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
